language: python

python:
  - 3.8

services:
  - docker

before_install:
  - docker build -t  prima_italica .

script:
  - docker run prima_italica /bin/sh -c "pytest"
  - docker run prima_italica /bin/sh -c "flake8"
  - pytest

