version: '3'

services:
  app:
    build: .
    container_name: prima_italica_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/django/app
    ports:
      # "host:container"
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: prima_italica_db
    # to access bash
    tty: true
    environment:
      - POSTGRES_DB=prima_italica
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - prima_italica_pgdata:/var/lib/postgresql/data


# Create volume on docker to avoid permission problems in the os.
# $docker volume create prima_italica_pgdata
volumes:
  prima_italica_pgdata:
    external: true