# Generated by Django 3.1.1 on 2020-09-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_acao', models.CharField(max_length=30)),
                ('instituicao_organizadora', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
